# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20170119_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='countries',
            field=models.ManyToManyField(related_name='visitors', to='travel.Country'),
        ),
    ]
