# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20170119_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='countries',
            new_name='visited_countries',
        ),
    ]
