# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 11:36
from __future__ import unicode_literals

from django.db import migrations, connection

def fix_m2m_table_name(apps, schema_editor):
    with connection.cursor() as cursor:
        tables = connection.introspection.table_names(cursor)
        if 'travel_userprofile_countries' in tables and 'travel_userprofile_visited_countries' not in tables:
            cursor.execute('ALTER TABLE "travel_userprofile_countries" RENAME TO "travel_userprofile_visited_countries"')

class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20170119_2112'),
    ]

    operations = [
        migrations.RunPython(fix_m2m_table_name, migrations.RunPython.noop),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
