# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20170124_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
