# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fid',
            field=models.BigIntegerField(),
        ),
    ]
